/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IPresalePoolInterface extends ethers.utils.Interface {
  functions: {
    "initialize(bytes32,address,address,address,uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class IPresalePool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IPresalePoolInterface;

  functions: {
    initialize(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(bytes32,address,address,address,uint256,uint256,uint256,uint256)"(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  initialize(
    _root: BytesLike,
    _soldToken: string,
    _offerToken: string,
    _fundingWallet: string,
    _openTime: BigNumberish,
    _duration: BigNumberish,
    _offeredCurrencyRate: BigNumberish,
    _offeredCurrencyDecimal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(bytes32,address,address,address,uint256,uint256,uint256,uint256)"(
    _root: BytesLike,
    _soldToken: string,
    _offerToken: string,
    _fundingWallet: string,
    _openTime: BigNumberish,
    _duration: BigNumberish,
    _offeredCurrencyRate: BigNumberish,
    _offeredCurrencyDecimal: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    initialize(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(bytes32,address,address,address,uint256,uint256,uint256,uint256)"(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    initialize(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(bytes32,address,address,address,uint256,uint256,uint256,uint256)"(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    initialize(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(bytes32,address,address,address,uint256,uint256,uint256,uint256)"(
      _root: BytesLike,
      _soldToken: string,
      _offerToken: string,
      _fundingWallet: string,
      _openTime: BigNumberish,
      _duration: BigNumberish,
      _offeredCurrencyRate: BigNumberish,
      _offeredCurrencyDecimal: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
